### PR TITLE
chore: Add AllContributors to README

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Closes https://github.com/scikit-hep/pylhe/issues/159.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @matthewfeickert, this is the "skeleton" to then get names added. I will take care of that once this gets reviewed and merged.

**Review by matthewfeickert — APPROVED** [review]
LGTM. Thanks!

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @matthewfeickert for maintenance, design, code, doc.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @lukasheinrich for maintenance, design, code, doc.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @eduardo-rodrigues for maintenance, code, doc.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @8me for code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @ariaradick for code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @jhgoh for code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @fuenfundachtzig for code.

**Comment by eduardo-rodrigues** [comment]
@all-contributors
please add @shantanu-gontia for code.

**Pull request merged**
