### PR TITLE
feat: Add IPython visualisation and switch to graphviz

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
This closes https://github.com/scikit-hep/pylhe/issues/63 and also deals in some way with https://github.com/scikit-hep/pylhe/issues/53.

Examples usage:
snapshot1

Easy also to save avoiding any coupling of dependencies:
snapshot2

```
* Add graphviz>=0.12.0 as a core dependency.
* Add graphviz.Digrap graph object as .graph property to LHEFile.
   - Add support for IPython visualization.
* Add test for LHEEvent_graph.
```

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
A few comments at this point:

- Using `graphviz` makes it simple to visualise events in notebooks, as per the example above. That's why this PR closes https://github.com/scikit-hep/pylhe/issues/63.
- From playing around a bit I found it rather evolved the way to get a particular event, which needs for example `itertools.islice`. I would suggest a follow-up issue to write a little wrapper function that returns the n-th event.
- I'm here removing the method `LHEEvent.visualize(...)`. I find it that it couples unnecessarily and also provides a rather indirect way of visualiing the graphs since the method involves internally calls with `dot2tex` and `tex2pix`, and finally the actual visualisation of the produced PDF file. To me this is effectively obsoleted with the way I show in this PR for how to display on the fly or get the DOT file or save it to standard formats. For the same reason I would then also delete the standalone function `visualize(...)`, thereby simplifying dependencies and couplings in design.

Seems good enough for a v0. Happy to hear your thoughts :-).

**Review by kratsg — APPROVED** [review]

**Comment by eduardo-rodrigues** [comment]
@lukasheinrich and/or @matthewfeickert, let me know what you think of this and also of removing the `visualize` function. I would be tempted to avoid a deprecated given that the user base is probably not gigantic. I would rather move towards a major release, which seems due (at least a minor release, if you think the present API is not quite OK for a 1.0). Thanks.

Note that the notebooks should then be refreshed and updated with more examples of functionality. I'm happy to help there, putting in this new functionality. Just let me know.

**Comment by eduardo-rodrigues** [comment]
Hello @lukasheinrich and @matthewfeickert, shall we converge on this and make a new release?

**Comment by matthewfeickert** [comment]
```python
import pylhe
from skhep_testdata import data_path
import itertools

lhe_file = data_path("pylhe-testfile-pr29.lhe")
events = pylhe.read_lhe_with_attributes(lhe_file)

print(f"Number of events: {pylhe.read_num_events(lhe_file)}")

event = next(itertools.islice(events, 1,2))
print(event.graph.source)

event.graph.render(filename="test", format="png")
```

is indeed a nice little example. :+1:

**Review by matthewfeickert — APPROVED** [review]
LGTM. :+1: Thanks @eduardo-rodrigues!

I'm going to write some short notes and then also release a new minor release given the addition of a new dependency. :+1:

**Comment by eduardo-rodrigues** [comment]
Sounds good, thanks. As soon as I find a bit of free time I will add this example as a get started in the README, if that's OK. I do find these little helpers a good thing.

**Pull request merged**
